### ISSUE TITLE
OfflineServer crashes on start if database is empty

### ISSUE THREAD

**Issue by berkay2578** [berkay2578/nfsw-server#3]
Occurs when there is no Persona or when a persona's garage is empty.

**Comment by trackmaniamatt** [comment]
Hey berkay. I downloaded the server as a .zip file, compiled the code, and tried to run it. But it crashes on startup for me still, even though it says this bug is fixed on here. Any ideas as to what might be up?

**Comment by berkay2578** [comment]
You have to get me the stack trace of the crash for me to say anything. You can also run the OfflineServer.exe with "/troubleshoot" and put the EventLog  in Data\Logs\ here.

**Comment by trackmaniamatt** [comment]
[EventLog.zip](https://github.com/berkay2578/nfsw-server/files/743519/EventLog.zip)

Here is the EventLog.log file of the crash.

**Comment by berkay2578** [comment]
You don't seem to have run it with "/troubleshoot". Also your code seems to be a bit behind, since the 59th line doesn't have the log.Info().

1. Download the latest code from here, although I strongly recommend the [GitHub extension](https://blogs.msdn.microsoft.com/benjaminperkins/2016/04/01/setting-up-and-using-github-in-visual-studio-2015/).
2. Empty the bin\Debug folder.
3. Set release mode to Debug-Any CPU, compile.
4. Run the OfflineServer from within the Visual Studio, as it will break on unhandled exceptions and log the exception to the Output.
5. Post both the stacktrace on the Output and the EventLog.log.

Follow these steps and I'll be able to assist you further.

**Comment by berkay2578** [comment]
Can you please try after commit cd836b8?

**Comment by trackmaniamatt** [comment]
it works now, thanks. :)
