### ISSUE TITLE
Compile problems. and File not found - AddonManager.exe

### ISSUE THREAD

**Issue by ghost** [berkay2578/nfsw-server#4]
I have a problem compile the code, it still shows an error.
 `1>
2>  File not found - AddonManager.exe
2>  0 File(s) copied
2>  The system cannot find the file specified.
2>  The system cannot find the file specified.
2>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(4291,5): error MSB3073: The command ""O:\IDM\nfsw-server-master_2\Extern\NetRevisionTool.exe" /restore "O:\IDM\nfsw-server-master_2\OfflineServer\"
2>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(4291,5): error MSB3073: xcopy /i /e /s /y /f "O:\IDM\nfsw-server-master_2\OfflineServer\Data\Settings\UI\*" "O:\IDM\nfsw-server-master_2\OfflineServer\bin\Debug\Data\UI"
2>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(4291,5): error MSB3073: xcopy /i /e /s /y /f "O:\IDM\nfsw-server-master_2\OfflineServer\Data\Server\*" "O:\IDM\nfsw-server-master_2\OfflineServer\bin\Debug\Data\Server"
2>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(4291,5): error MSB3073: xcopy /i /e /s /y /f "O:\IDM\nfsw-server-master_2\OfflineServer\Data\Others\*" "O:\IDM\nfsw-server-master_2\OfflineServer\bin\Debug\Data\Others"
2>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(4291,5): error MSB3073: xcopy /i /e /s /y /f **"O:\IDM\nfsw-server-master_2\AddonManager\bin\Release\**AddonManager.exe** "O:\IDM\nfsw-server-master_2\OfflineServer\bin\Debug\"
2>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(4291,5): error MSB3073: IF EXIST "O:\IDM\nfsw-server-master_2\OfflineServer\bin\Debug\x86\SQLite.Interop.dll" xcopy /i /e /s /y /f "O:\IDM\nfsw-server-master_2\OfflineServer\bin\Debug\x86\SQLite.Interop.dll" "O:\IDM\nfsw-server-master_2\OfflineServer\costura32\*"
2>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(4291,5): error MSB3073: IF EXIST "O:\IDM\nfsw-server-master_2\OfflineServer\bin\Debug\x64\SQLite.Interop.dll" xcopy /i /e /s /y /f "O:\IDM\nfsw-server-master_2\OfflineServer\bin\Debug\x64\SQLite.Interop.dll" "O:\IDM\nfsw-server-master_2\OfflineServer\costura64\*"
2>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(4291,5): error MSB3073: rd /s /q "O:\IDM\nfsw-server-master_2\OfflineServer\bin\Debug\x86" ""O:\IDM\nfsw-server-master_2\OfflineServer\bin\Debug\x64"" exited with code 4.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by berkay2578** [comment]
Could you try changing the project build order to 
1. AddonManager
2. OfflineServer
and see if that helps?

Code 4 is Cannot Access File or verbosely 
> Initialization error occurred. There is not enough memory or disk space, or you entered an invalid drive name or invalid syntax on the command line.

**Comment by ghost** [comment]
I had to install the add-on for MS Nuget studio 2012.
http://download.microsoft.com/download/6/F/C/6FC19DBF-C223-41D0-835A-BD2155BC950D/U3-20160802.1/VSToolsForWindows1C.exe

Problem with MSVS solved,but in nfsw I discovered another problem.
In the game when you select a car and follow him want to buy, show error message.
I want to buy White Volkswagen Scirocco ,but the game is against.

CAR PURCHASE FAILED
AN ERROR HAS OCCURRED
AN ERROR HAS OCCURRED  WHILE PURCHASING YOUR CAR - PLEASE TRY AGAIN.
Cars have a price tag of zero values.


And when I added one car in the garage (Launcher) game Startup, and then clicking "Enter World" I froze.
LOGS:
[Logs.zip](https://github.com/berkay2578/nfsw-server/files/749186/Logs.zip)

**Comment by berkay2578** [comment]
The server isn't read for standalone usage yet, it needs .xml files as fallback to properly launch the game. I still haven't decided what to do yet so that's why you're not able to actually play the game. The infinite loading when you click "Enter World" happens because of this, too.

The basket bug, what made you unable to purchase cars, was fixed in commit 3e0c57e.

**Comment by ghost** [comment]
How did he find out that this part is to the hash code?
t0_custom_brakes_pro_uncommonrarity
`
<ProductTrans>
		<BundleItems i:nil="true"/>CategoryId i:nil="true"/><Currency>CASH</Currency>
		<Description/>
		<DurationMinute>0</DurationMinute>
		**<Hash>3334365598</Hash>**
		<Icon>r3_engine_gold</Icon>
		<Level>0</Level>
		<LongDescription>PRO SERIES</LongDescription>
		<Price>1000000.0000</Price>
		<Priority>1</Priority>
		<ProductId>SRV-PERF1</ProductId>
		<ProductTitle>CUSTOM BRAKES</ProductTitle>
		<ProductType>PERFORMANCEPART</ProductType>
		<SecondaryIcon/>
		<UseCount>1</UseCount>
		<VisualStyle/>
		<WebIcon/>
		<WebLocation/>
	</ProductTrans>
'

**Comment by berkay2578** [comment]
Damn, GitHub is amazing.

This is getting off-topic now, your issue was fixed so I'm closing it.
