### ISSUE TITLE
Null exception while running OfflineServer.exe debug

### ISSUE THREAD

**Issue by HeyImRuu** [berkay2578/nfsw-server#5]
using current commit: 7f79f3d

Trying to run the server through visual studio gives a null exception error on [line 297](https://github.com/berkay2578/nfsw-server/blob/master/OfflineServer/Persona.cs#L297) of Persona.cs
[EventLog.log](http://pastebin.com/qVmz2x3w)
Am I missing something or is there a legit issue here?

**Comment by berkay2578** [comment]
The log seems genuinely fine, but it seems it's not requesting the persona name on launch which leads me to think that this server ran for you beforehand. Can you delete the Server.db and try again? This might be a schema update bug.

**Comment by HeyImRuu** [comment]
Issue now resolved. Deleting the Server.db worked. Thank you.
