### ISSUE TITLE
Error Reading resource SQLite.Interop.dll

### ISSUE THREAD

**Issue by Dokman** [berkay2578/nfsw-server#7]
Error CS1566 Error reading resource 'OfflineServer.costura32.SQLite.Interop.dll': ' Could not find file' D:\Repos \nfsw-server\OfflineServer\costura32 \SQLite.Interop.dll '.' OfflineServer D:\Repos\nfsw-server\OfflineServer \

**Comment by berkay2578** [comment]
Build the project once and you will execute the following post-build events:
```
IF EXIST "$(ProjectDir)$(OutDir)x86\SQLite.Interop.dll" xcopy /i /e /s /y /f "$(ProjectDir)$(OutDir)x86\SQLite.Interop.dll" "$(ProjectDir)costura32\*"
IF EXIST "$(ProjectDir)$(OutDir)x64\SQLite.Interop.dll" xcopy /i /e /s /y /f "$(ProjectDir)$(OutDir)x64\SQLite.Interop.dll" "$(ProjectDir)costura64\*"
rd /s /q "$(ProjectDir)$(OutDir)x86" ""$(ProjectDir)$(OutDir)x64"
```

Build the project again and you will have costura folders set-up.
